data:
  # We only have one dataset anyway
  dataset:
    name: MiddleFrameDataset
    prefix: "path/to/hdf/directory"
    files: !include "path/to/data-split.yml"
    resize: "center"
  num_workers: 4

network:
  optimizer:
    name: Adam
    lr: 1.e-3
  metrics: # Those are the one always computed and identical for all parameters
    # Monai's metrics
    - display_name: hdf95
      name: HausdorffDistance95
    - display_name: masd
      name: SurfaceDistance
  spatial_dims: 3
  in_channels: 1 # Gray scale all the time


tester:
  accelerator: gpu
  devices: 1
