data:
  # We only have one dataset anyway
  dataset:
    name: MiddleFrameDataset
    prefix: "~/Documents/data/"
    files: !include "~/Documents/data/data-split.yml"
    resize: "center"
    contrast: 2
  num_workers: 4

network:
  optimizer:
    name: Adam
    lr: 1.e-4
  metrics: # Those are the one always computed and identical for all parameters
    # Torchmetrics
    - display_name: dice
      name: Dice
    # Monai's metrics
    - display_name: hdf95
      name: HausdorffDistance95
    - display_name: masd
      name: SurfaceDistance
  spatial_dims: 3
  in_channels: 1 # Gray scale all the time


tester:
  accelerator: gpu
  devices: 1
