data:
  dataset:
    name: HDFDataset
    prefix: "~/Documents/data/sub_hdf"
    # FIXME: Consider separate file for train/test/val?
    files: !include "~/Documents/data/sub_hdf/data-split.yml"
  batch_size: 1

network:
  name: BasicUNet
  loss:
    name: CrossEntropyLoss
  # Define interesting metrics here
  metrics:
    - display_name: acc
      name: Accuracy
      kwargs:
        mdmc_average: global
  spatial_dims: 3
  in_channels: 1 # Gray scale
  out_channels: 1
  features: [8, 16, 32]

trainer:
  max_epochs: 3
